export const gagInfo = [
    {
        id:1,
        gag:'Feather',
        gagType:'Toon-Up',
        prestige:'',
        organic:'',
        minRange:'',
        maxRange:''
    },
    {
        id:2,
        gag:'Megaphone',
        gagType:'Toon-Up',
        prestige:'',
        organic:'',
        minRange:'',
        maxrange:''
    },
    {
        id:3,
        gag:'Lipstick',
        gagType:'Toon-Up',
        prestige:'',
        organic:'',
        minRange:'',
        maxrange:''
    },
    {
        id:4,
        gag:'Bamboo Cane',
        gagType:'Toon-Up',
        prestige:'',
        organic:'',
        minRange:'',
        maxRange:''
    },
    {
        id:5,
        gag:'Pixie Dust',
        gagType:'Toon-Up',
        prestige:'',
        organic:'',
        minRange:'',
        maxRange:''
    },
    {
        id:6,
        gag:'Juggling Cubes',
        gagType:'Toon-Up',
        prestige:'',
        organic:'',
        minRange:'',
        maxRange:''
    },
    {
        id:7,
        gag:'Confetti Cannon',
        gagType:'Toon-Up',
        prestige:'',
        organic:'',
        minRange:'',
        maxRange:''
    },
    {
        id:8,
        gag:'High Dive',
        gagType:'Toon-Up',
        prestige:'',
        organic:'',
        minRange:'',
        maxRange:''
    },
    {
        id:9,
        gag:'Banana Peel',
        gagType:'Trap',
        prestige:'',
        organic:'',
        minRange:18,
        maxRange:65
    },
    {
        id:10,
        gag:'Rake',
        gagType:'Trap',
        prestige:'',
        organic:'',
        minRange:25,
        maxRange:70
    },
    {
        id:11,
        gag:'Spring Board',
        gagType:'Trap',
        prestige:'',
        organic:'',
        minRange:40,
        maxRange:90
    },
    {
        id:12,
        gag:'Marbles',
        gagType:'Trap',
        prestige:'',
        organic:'',
        minRange:55,
        maxRange:110
    },
    {
        id:13,
        gag:'Quicksand',
        gagType:'Trap',
        prestige:'',
        organic:'',
        minRange:75,
        maxRange:135
    },
    {
        id:14,
        gag:'Trapdoor',
        gagType:'Trap',
        prestige:'',
        organic:'',
        minRange:100,
        maxRange:185
    },
    {
        id:15,
        gag:'Wrecking Ball',
        gagType:'Trap',
        prestige:'',
        organic:'',
        minRange:160,
        maxRange:245
    },
    {
        id:16,
        gag:'TNT',
        gagType:'Trap',
        prestige:'',
        organic:'',
        minRange:220,
        maxRange:285
    },
    {
        id:17,
        gag:'Dollar Bill',
        gagType:'Lure',
        prestige:'',
        organic:'',
        minRange:'',
        maxRange:'',
        knockBack:1.5
    },
    {
        id:18,
        gag:'Small Magnet',
        gagType:'Lure',
        prestige:'',
        organic:'',
        minRange:'',
        maxRange:'',
        knockBack:1.5
    },
    {
        id:19,
        gag:'5 Dollar Bill',
        gagType:'Lure',
        prestige:'',
        organic:'',
        minRange:'',
        maxRange:'',
        knockBack:1.5
    },
    {
        id:20,
        gag:'Big Magnet',
        gagType:'Lure',
        prestige:'',
        organic:'',
        minRange:'',
        maxRange:'',
        knockBack:1.5
    },
    {
        id:21,
        gag:'10 Dollar Bill',
        gagType:'Lure',
        prestige:'',
        organic:'',
        minRange:'',
        maxRange:'',
        knockBack:1.5
    },
    {
        id:22,
        gag:'Hypno Goggles',
        gagType:'Lure',
        prestige:'',
        organic:'',
        minRange:'',
        maxRange:'',
        knockBack:1.5
    },
    {
        id:23,
        gag:'50 Dollar Bill',
        gagType:'Lure',
        prestige:'',
        organic:'',
        minRange:'',
        maxRange:'',
        knockBack:1.5
    },
    {
        id:24,
        gag:'Presentation',
        gagType:'Lure',
        prestige:'',
        organic:'',
        minRange:'',
        maxRange:'',
        knockBack:1.5
    },
    {
        id:25,
        gag:'Kazoo',
        gagType:'Sound',
        prestige:'',
        organic:'',
        minRange:3,
        maxRange:14
    },
    {
        id:26,
        gag:'Bike Horn',
        gagType:'Sound',
        prestige:'',
        organic:'',
        minRange:5,
        maxrange:16
    },
    {
        id:27,
        gag:'Whistle',
        gagType:'Sound',
        prestige:'',
        organic:'',
        minRange:9,
        maxrange:20
    },
    {
        id:28,
        gag:'Bugle',
        gagType:'Sound',
        prestige:'',
        organic:'',
        minRange:14,
        maxRange:25
    },
    {
        id:29,
        gag:'Aoogah',
        gagType:'Sound',
        prestige:'',
        organic:'',
        minRange:19,
        maxRange:30
    },
    {
        id:30,
        gag:'Elephant Trunk',
        gagType:'Sound',
        prestige:'',
        organic:'',
        minRange:26,
        maxRange:37
    },
    {
        id:31,
        gag:'Foghorn',
        gagType:'Sound',
        prestige:'',
        organic:'',
        minRange:35,
        maxRange:65
    },
    {
        id:32,
        gag:'Opera Singer',
        gagType:'Sound',
        prestige:'',
        organic:'',
        minRange:55,
        maxRange:76
    },
    {
        id:33,
        gag:'Squirting Flower',
        gagType:'Squirt',
        prestige:'',
        organic:'',
        minRange:3,
        maxRange:4
    },
    {
        id:34,
        gag:'Glass of Water',
        gagType:'Squirt',
        prestige:'',
        organic:'',
        minRange:6,
        maxRange:8
    },
    {
        id:35,
        gag:'Squirt Gun',
        gagType:'Squirt',
        prestige:'',
        organic:'',
        minRange:10,
        maxRange:12
    },
    {
        id:36,
        gag:'Water Balloon',
        gagType:'Squirt',
        prestige:'',
        organic:'',
        minRange:18,
        maxRange:21
    },
    {
        id:37,
        gag:'Seltzer Bottle',
        gagType:'Squirt',
        prestige:'',
        organic:'',
        minRange:27,
        maxRange:30
    },
    {
        id:38,
        gag:'Fire Hose',
        gagType:'Squirt',
        prestige:'',
        organic:'',
        minRange:45,
        maxRange:56
    },
    {
        id:39,
        gag:'Storm Cloud',
        gagType:'Squirt',
        prestige:'',
        organic:'',
        minRange:60,
        maxRange:80
    },
    {
        id:40,
        gag:'Geyser',
        gagType:'Squirt',
        prestige:'',
        organic:'',
        minRange:90,
        maxRange:115
    },
    {
        id:41,
        gag:'Joy Buzzer',
        gagType:'Zap',
        prestige:'',
        organic:'',
        minRange:3,
        maxRange:12
    },
    {
        id:42,
        gag:'Rug',
        gagType:'Zap',
        prestige:'',
        organic:'',
        minRange:5,
        maxRange:18
    },
    {
        id:43,
        gag:'Balloon',
        gagType:'Zap',
        prestige:'',
        organic:'',
        minRange:8,
        maxRange:30
    },
    {
        id:44,
        gag:'Kart Battery',
        gagType:'Zap',
        prestige:'',
        organic:'',
        minRange:14,
        maxRange:48
    },
    {
        id:45,
        gag:'Taser',
        gagType:'Zap',
        prestige:'',
        organic:'',
        minRange:21,
        maxRange:72
    },
    {
        id:46,
        gag:'Broken TV',
        gagType:'Zap',
        prestige:'',
        organic:'',
        minRange:35,
        maxRange:120
    },
    {
        id:47,
        gag:'Tesla Coil',
        gagType:'Zap',
        prestige:'',
        organic:'',
        minRange:50,
        maxRange:198
    },
    {
        id:48,
        gag:'Lightning',
        gagType:'Zap',
        prestige:'',
        organic:'',
        minRange:70,
        maxRange:240
    },
    {
        id:49,
        gag:'Cupcake',
        gagType:'Throw',
        prestige:'',
        organic:'',
        minRange:5,
        maxRange:9
    },
    {
        id:50,
        gag:'Fruit Pie Slice',
        gagType:'Throw',
        prestige:'',
        organic:'',
        minRange:8,
        maxRange:13
    },
    {
        id:51,
        gag:'Cream Pie Slice',
        gagType:'Throw',
        prestige:'',
        organic:'',
        minRange:15,
        maxRange:21
    },
    {
        id:52,
        gag:'Birthday Cake Slice',
        gagType:'Throw',
        prestige:'',
        organic:'',
        minRange:28,
        maxRange:35
    },
    {
        id:53,
        gag:'Whole Fruit Pie',
        gagType:'Throw',
        prestige:'',
        organic:'',
        minRange:40,
        maxRange:52
    },
    {
        id:54,
        gag:'Whole Cream Pie',
        gagType:'Throw',
        prestige:'',
        organic:'',
        minRange:55,
        maxRange:87
    },
    {
        id:55,
        gag:'Birthday Cake',
        gagType:'Throw',
        prestige:'',
        organic:'',
        minRange:85,
        maxRange:127
    },
    {
        id:56,
        gag:'Wedding Cake',
        gagType:'Throw',
        prestige:'',
        organic:'',
        minRange:120,
        maxRange:167 
    },
    {
        id:57,
        gag:'Flower Pot',
        gagType:'Drop',
        prestige:'',
        organic:'',
        minRange:10,
        maxRange:12 
    },
    {
        id:58,
        gag:'Sandbag',
        gagType:'Drop',
        prestige:'',
        organic:'',
        minRange:18,
        maxRange:20 
    },
    {
        id:59,
        gag:'Bowling Ball',
        gagType:'Drop',
        prestige:'',
        organic:'',
        minRange:30,
        maxRange:35 
    },
    {
        id:60,
        gag:'Anvil',
        gagType:'Drop',
        prestige:'',
        organic:'',
        minRange:45,
        maxRange:55 
    },
    {
        id:61,
        gag:'Big Weight',
        gagType:'Drop',
        prestige:'',
        organic:'',
        minRange:65,
        maxRange: 80
    },
    {
        id:62,
        gag:'Safe',
        gagType:'Drop',
        prestige:'',
        organic:'',
        minRange:90,
        maxRange:125 
    },
    {
        id:63,
        gag:'Boulder',
        gagType:'Drop',
        prestige:'',
        organic:'',
        minRange:145,
        maxRange:180
    },
    {
        id:64,
        gag:'Grand Piano',
        gagType:'Drop',
        prestige:'',
        organic:'',
        minRange:200,
        maxRange:220
    },
]