export const toons = [
    {
        id:1,
        gag:'Pick a gag!',
        gagType:9,
        name:'Toon 1',
        prestige:false,
        organic:'',
        minRange:0,
        midRange:0,
        maxRange:0,
        normalMinRange:0,
        normalMidRange:0,
        normalMaxRange:60,
        prestigeMinRange:0,
        prestigeMidRange:0,
        prestigeMaxRange:0
    },
    {
        id:2,
        gag:'Pick a gag!',
        gagType:9,
        name:'Toon 2',
        prestige:false,
        organic:'',
        minRange:0,
        midRange:0,
        maxRange:0,
        normalMinRange:0,
        normalMidRange:0,
        normalMaxRange:60,
        prestigeMinRange:0,
        prestigeMidRange:0,
        prestigeMaxRange:0
    },
    {
        id:3,
        gag:'Pick a gag!',
        gagType:9,
        name:'Toon 3',
        prestige:false,
        organic:'',
        minRange:0,
        midRange:0,
        maxRange:0,
        normalMinRange:0,
        normalMidRange:0,
        normalMaxRange:60,
        prestigeMinRange:0,
        prestigeMidRange:0,
        prestigeMaxRange:0
    },
    {
        id:4,
        gag:'Pick a gag!',
        gagType:9,
        name:'Toon 4',
        prestige:false,
        organic:'',
        minRange:0,
        midRange:0,
        maxRange:0,
        normalMinRange:0,
        normalMidRange:0,
        normalMaxRange:60,
        prestigeMinRange:0,
        prestigeMidRange:0,
        prestigeMaxRange:0
    },
]